#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

data="${OPENSHIFT_DATA_DIR}/assets"
assets="${OPENSHIFT_REPO_DIR}/public"

# Remove the assets directory if it's empty
cp -rf $assets/assets $OPENSHIFT_DATA_DIR
find $assets/assets -maxdepth 0 -type d -empty -delete 2> /dev/null

# Try to make the symlink
ln -s -f $data $assets 2> /dev/null
if [ $? -gt 0 ]; then
  echo "Unable to create symlink to assets directory, using existing directory in repository"
fi
